IACS-683 fix azure frontend adapter

diff --git a/todo-app/frontend/.valuestream/output/manifests.yml b/todo-app/frontend/.valuestream/output/manifests.yml
--- a/todo-app/frontend/.valuestream/output/manifests.yml
+++ b/todo-app/frontend/.valuestream/output/manifests.yml
@@ -965,8 +965,14 @@ spec:
       image: swacli/static-web-apps-cli:1.1.6
       name: deploy
       script: |-
-        az login --service-principal -u "${AZURE_CLIENT_ID}" -p "${AZURE_CLIENT_SECRET}" --tenant "${AZURE_TENANT_ID}"
-        swa deploy $(params.deployTargetDir) --no-use-keychain --deployment-token $(az staticwebapp secrets list --name ${SWA_CLI_APP_NAME} --resource-group ${AZURE_RESOURCE_GROUP} --query "properties.apiKey" | tr -d '"')
+        #!/usr/bin/env bash
+        az login --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} --tenant ${AZURE_TENANT_ID} --output none
+        RESOURCE_EXISTENCE_CHECK=$(az staticwebapp show --name ${SWA_CLI_APP_NAME} --resource-group ${AZURE_RESOURCE_GROUP} 2>&1 > /dev/null)
+        if [[ $RESOURCE_EXISTENCE_CHECK == "ERROR: (ResourceNotFound)"* ]]; then
+          echo "SKIP: azure static web app not found"
+        else
+          swa deploy $(params.deployTargetDir) --no-use-keychain --deployment-token $(az staticwebapp secrets list --name ${SWA_CLI_APP_NAME} --resource-group ${AZURE_RESOURCE_GROUP} --query "properties.apiKey" | tr -d '"')
+        fi
       securityContext:
         runAsUser: 0
       workingDir: $(workspaces.shared.path)/source
@@ -1014,12 +1020,21 @@ spec:
       image: mcr.microsoft.com/azure-cli:2.57.0
       name: geturl
       script: |-
-        az login --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} --tenant ${AZURE_TENANT_ID}
-        # get url of custom domain url
-        result=$(az staticwebapp hostname list --name $(params.appName) --resource-group $(params.azureResourceGroupName) --query '[].domainName' -o tsv || true)
-        if [ -n "${result}" ]; then
-        	scheme='https://'
-        	echo "${scheme}${result}" | tee /tekton/results/publicUrl
+        #!/usr/bin/env bash
+        az login --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} --tenant ${AZURE_TENANT_ID} --output none
+        RESOURCE_EXISTENCE_CHECK=$(az staticwebapp show --name ${SWA_CLI_APP_NAME} --resource-group ${AZURE_RESOURCE_GROUP} 2>&1 > /dev/null)
+        if [[ $RESOURCE_EXISTENCE_CHECK == "ERROR: (ResourceNotFound)"* ]]; then
+          echo "SKIP: azure static web app not found"
+          echo "" > /tekton/results/publicUrl
+        else
+          # get url of custom domain url
+          result=$(az staticwebapp hostname list --name ${SWA_CLI_APP_NAME} --resource-group ${AZURE_RESOURCE_GROUP} --query '[].domainName' -o tsv || true)
+          if [ -n "${result}" ]; then
+            scheme='https://'
+            echo "${scheme}${result}" | tee /tekton/results/publicUrl
+          else
+            echo "" > /tekton/results/publicUrl
+          fi
         fi
       workingDir: $(workspaces.shared.path)/source
   workspaces:
